### ISSUE TITLE
problems with some common modules

### ISSUE THREAD

**Issue by mcollina** [vercel/node-file-trace#112]
I have been trying to use this module to detect the tree of files used by a few of my apps, and it's missing a few.

Specially it does not load https://github.com/nodejs/readable-stream/blob/master/lib/internal/streams/buffer_list.js and others in that repo.

**Comment by styfle** [comment]
Hi @mcollina 

Can you provide the steps to reproduce this issue?

There is likely a dynamic require somewhere that cannot be analyzed easily.

**Comment by styfle** [comment]
Closing since its not clear what the problem is and what inputs were used.
