### ISSUE TITLE
Incorrect readme usage instructions

### ISSUE THREAD

**Issue by jaydenseric** [vercel/node-file-trace#140]
The readme usage section incorrectly instructs that `nodeFileTrace` can be required like so:

```js
const nodeFileTrace = require('@zeit/node-file-trace');
```

<img width="300" alt="Screen Shot 2020-07-27 at 5 03 12 pm" src="https://user-images.githubusercontent.com/1754873/88513242-43ed0780-d02b-11ea-9a4b-2bf5132adc38.png">

When really, it must be required like this:

```js
const { nodeFileTrace } = require('@zeit/node-file-trace');
```

**Comment by styfle** [comment]
Thanks! Fixed in #142 👍
