### ISSUE TITLE
fs.readFile trigger

### ISSUE THREAD

**Issue by guybedford** [vercel/node-file-trace#16]
We should be triggering asset emission on `fs.readFile` arguments, even if those arguments might be "ambiguous strings" from an asset analysis perspective:

```js
const fs = require('fs');
fs.readFile('./symlink');
```

This can be done with the existing `[TRIGGER]` system in place in the analysis, it just needs to be set up.

**Comment by styfle** [comment]
@guybedford Is this still needed or was it already implemented?

**Comment by guybedford** [comment]
FS functions are still not direct triggers for emission I don't believe.

That is I think the above case will still not do an emission but it could be worth verifying this.

**Comment by guybedford** [comment]
Hmm actually it seems like the above example should be working? In that case we can close this.
