### ISSUE TITLE
Cleaning up modules removes necessary files

### ISSUE THREAD

**Issue by balajmarius** [vercel/node-file-trace#48]
Hello,

I'm trying to deploy with `now` (v.2) a monorepo project which uses [svgo](https://github.com/svg/svgo), and `svgo` is using a default config file from `node_modules/svgo/.svgo.yml`.

♻️ During the build phase, on step [5/5] when `now` is cleaning modules the `.svgo.yml` file is removed.

I tried to add a `.yarnclean` file with `!.svgo.yml` inside but no success.

Any ideas how can I prevent the cleanup step or fix this?

```
Error: ENOENT: no such file or directory, open '//../../.svgo.yml'
 ```

The `svgo` [issue](https://github.com/svg/svgo/issues/622).

**Comment by styfle** [comment]
I am unable to reproduce the issue with the latest `node-file-trace` and latest `svgo`.

```sh
npm i -g @zeit/node-file-trace
mkdir example && cd example
yarn add svgo
echo "const svgo = require('svgo')" > index.js
nft print index.js | grep yml
# prints "node_modules/svgo/.svgo.yml"
```

This prints the expected `node_modules/svgo/.svgo.yml`.
